### ISSUE TITLE
Unable to compile ffmpeg in arm64-v8a

### ISSUE THREAD

**Issue by BahaaIddinSharqawi** [cmeng-git/ffmpeg-android#1]
When I tried to compile ffmpeg with libvpx in arm64-v8a, the build process fails with error:
 "ERROR: libvpx decoder version must be >=0.9.1",
The libvpx.a is generated successfully but the ffmpeg skipped it (because incompatible reason).
This error occurs when only compile for arm64-v8a although I followed all your *.sh files.
Also I tried build using your .sh files but no fix for this error.
Thank you.

**Comment by cmeng-git** [comment]
I also faced similar problem in the past, even when the build say it is OK; If the library configuration file is not properly written for the mentioned architecture, it may actually build library for 32-bit instead of 64-bit even if you defined 64-bit architecture. This problem however will immediately show up when you trying to integrate into the ffmpeg for the 64-bit architecture due to libraries incompatibility.

If you review the log for the libvpx arm64-8a library build, it may give you insight the actual build library architecture.

Below was my observation, seems that the 64-bit built is using incorrect cc for compilation / linking:
> libvpx-1.7.0:
> 1. ndk-r15c (build all except mips and mips64; ndk-r16b built has errors - see vpx_build.sh);
> 2. configure with Target=arm64-android-gcc has error which uses incorrect cc i.e. arm-linux-androideabi-gcc;

For this type of the problem, you need to find if there is a new update of the libraries (configuration) or someone online has provided a solution with patch to the configuration file.

**Comment by cmeng-git** [comment]
Here is the patch to libvpx-1.7.0 configure.sh for the arm64-v8a build.
[libvpx_configure.sh-1.7.0.zip](https://github.com/cmeng-git/ffmpeg-android/files/2985986/libvpx_configure.sh-1.7.0.zip)

**Comment by BahaaIddinSharqawi** [comment]
Thank you, I will try with it.

**Comment by cmeng-git** [comment]
There are other patches required to fix x86 and x86_64 problems. You can refer to vpx-android repository for details.

**Comment by BahaaIddinSharqawi** [comment]
Before I use your libvpx-1.7.0 patch for arm64-v8a architecture, I compiled libvpx-1.8.0 for target armv8-linux-gcc (which is compatible with armv64-v8a) then the ffmpeg accepted the compiled libvpx (armv8) and the compilation process for arm64-v8a is done without any problem. I tested the ffmpeg in real device supports arm64-v8a and libvpx worked fine.

Thank you for your help..

**Comment by cmeng-git** [comment]
Glade the patches fixed your problem. Issue closed.

**Comment by cmeng-git** [comment]
Latest update from vpx team:
https://bugs.chromium.org/p/webm/issues/detail?id=1622#c3
